{% set name = "pyaspeller" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyaspeller-{{ version }}.tar.gz
  sha256: 41e4291ef68dfc4da9b6f1eab42deb699956a3a73c8c35f4ff5d55c104d18d42

build:
  entry_points:
    - pyaspeller = pyaspeller.__init__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry >=0.12
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - requests >=2.27.1,<3.0.0

test:
  imports:
    - pyaspeller
  commands:
    - pip check
    - pyaspeller --help
  requires:
    - pip

about:
  home: https://github.com/oriontvv/pyaspeller
  summary: Search tool typos in the text, files and websites.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
